
import { Achievement } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
    // QUEST MILESTONES
    {
        id: 'first_blood',
        title: 'First Blood',
        description: 'Complete your first quest',
        icon: 'Sword',
        rarity: 'common',
        condition: 'Complete 1 quest',
        xpBonus: 50,
    },
    {
        id: 'quest_hunter',
        title: 'Quest Hunter',
        description: 'Complete 10 quests',
        icon: 'Target',
        rarity: 'common',
        condition: 'Complete 10 quests',
        xpBonus: 100,
    },
    {
        id: 'century_mark',
        title: 'Century Mark',
        description: 'Complete 100 quests',
        icon: 'Crown',
        rarity: 'epic',
        condition: 'Complete 100 quests',
        xpBonus: 500,
    },
    {
        id: 'legend_rises',
        title: 'Legend Rises',
        description: 'Complete 500 quests',
        icon: 'Trophy',
        rarity: 'legendary',
        condition: 'Complete 500 quests',
        xpBonus: 2000,
    },

    // STREAKS
    {
        id: 'consistent_soul',
        title: 'Consistent Soul',
        description: 'Maintain a 3-day streak',
        icon: 'Flame',
        rarity: 'common',
        condition: '3-day streak',
        xpBonus: 75,
    },
    {
        id: 'week_warrior',
        title: 'Week Warrior',
        description: 'Maintain a 7-day streak',
        icon: 'Calendar',
        rarity: 'rare',
        condition: '7-day streak',
        xpBonus: 200,
    },
    {
        id: 'unstoppable_force',
        title: 'Unstoppable Force',
        description: 'Maintain a 30-day streak',
        icon: 'Infinity',
        rarity: 'legendary',
        condition: '30-day streak',
        xpBonus: 1000,
    },

    // DIFFICULTY
    {
        id: 'dragonslayer',
        title: 'Dragonslayer',
        description: 'Complete a Legendary quest',
        icon: 'Dragon',
        rarity: 'rare',
        condition: '1 legendary quest',
        xpBonus: 300,
    },
    {
        id: 'hard_boiled',
        title: 'Hard Boiled',
        description: 'Complete 10 Hard quests',
        icon: 'Shield',
        rarity: 'epic',
        condition: '10 hard quests',
        xpBonus: 500,
    },

    // LEVELING
    {
        id: 'awakening',
        title: 'Awakening',
        description: 'Reach Level 5',
        icon: 'Sparkles',
        rarity: 'common',
        condition: 'Reach level 5',
        xpBonus: 100,
    },
    {
        id: 'ascendant',
        title: 'Ascendant',
        description: 'Reach Level 20',
        icon: 'Mountain',
        rarity: 'epic',
        condition: 'Reach level 20',
        xpBonus: 750,
    },
    {
        id: 'transcendent',
        title: 'Transcendent',
        description: 'Reach Level 50',
        icon: 'Stars',
        rarity: 'legendary',
        condition: 'Reach level 50',
        xpBonus: 2500,
    },

    // CATEGORIES
    {
        id: 'iron_body',
        title: 'Iron Body',
        description: 'Complete 20 health quests',
        icon: 'Dumbbell',
        rarity: 'rare',
        condition: '20 health quests',
        xpBonus: 250,
    },
    {
        id: 'scholars_path',
        title: 'Scholar\'s Path',
        description: 'Complete 20 learning quests',
        icon: 'Book',
        rarity: 'rare',
        condition: '20 learning quests',
        xpBonus: 250,
    },

    // SPECIAL
    {
        id: 'soul_seeker',
        title: 'Soul Seeker',
        description: 'Have your first conversation with Future Self',
        icon: 'MessageCircle',
        rarity: 'common',
        condition: '1 future self message',
        xpBonus: 50,
    },
    {
        id: 'time_traveler',
        title: 'Time Traveler',
        description: 'Have 50 Future Self conversations',
        icon: 'Clock',
        rarity: 'epic',
        condition: '50 future self messages',
        xpBonus: 500,
    },
    {
        id: 'the_comeback',
        title: 'The Comeback',
        description: 'Complete 5 quests after a 7-day gap',
        icon: 'RotateCcw',
        rarity: 'rare',
        condition: '5 quests after gap',
        xpBonus: 300,
    },
    {
        id: 'speed_runner',
        title: 'Speed Runner',
        description: 'Complete 5 quests in one day',
        icon: 'Zap',
        rarity: 'rare',
        condition: '5 quests in 1 day',
        xpBonus: 200,
    },
    {
        id: 'night_owl',
        title: 'Night Owl',
        description: 'Complete a quest after midnight',
        icon: 'Moon',
        rarity: 'common',
        condition: 'Complete quest 00:00-04:00',
        xpBonus: 100,
    },
    {
        id: 'early_bird',
        title: 'Early Bird',
        description: 'Complete a quest before 7am',
        icon: 'Sun',
        rarity: 'common',
        condition: 'Complete quest 04:00-07:00',
        xpBonus: 100,
    },
];
